apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-speedrun-be-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-speedrun-be
  template:
    metadata:
      labels:
        app: k8s-speedrun-be
    spec:
      containers:
        - name: k8s-speedrun-be-container
          image: paolodapul/k8s-speedrun-be:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-speedrun-be-service
  namespace: development
spec:
  type: NodePort # Use LoadBalancer if deploying in a cloud environment that supports it, or ClusterIP for internal access.
  selector:
    app: k8s-speedrun-be # Ensures the service routes traffic to the correct pods.
  ports:
    - port: 3000 # The port the service will serve on.
      targetPort: 3000 # The container port to which traffic will be routed.
      nodePort: 30090 # Optionally specify if you want a specific port on the node; this is only needed for NodePort.
