apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-speedrun-fe-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-speedrun-fe
  template:
    metadata:
      labels:
        app: k8s-speedrun-fe
    spec:
      containers:
        - name: k8s-speedrun-fe-container
          image: paolodapul/k8s-speedrun-fe:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-speedrun-fe-service
  namespace: development
spec:
  type: NodePort # Use LoadBalancer if deploying in a cloud environment that supports it, or ClusterIP for internal access.
  selector:
    app: k8s-speedrun-fe # Ensures the service routes traffic to the correct pods.
  ports:
    - port: 80 # The port the service will serve on.
      targetPort: 80 # The container port to which traffic will be routed.
      nodePort: 30080 # Optionally specify if you want a specific port on the node; this is only needed for NodePort.
